// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"time"
)

type Link struct {
	ID         int64
	Code       string
	Url        string
	CreatedAt  time.Time
	ClickCount int64
}
