// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"
	"time"
)

const checkIfCodeExistsFromUrl = `-- name: CheckIfCodeExistsFromUrl :one
SELECT code FROM links
WHERE url = $1
`

func (q *Queries) CheckIfCodeExistsFromUrl(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkIfCodeExistsFromUrl, url)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getDataFromCode = `-- name: GetDataFromCode :one
SELECT url, created_at FROM links
WHERE code = $1
`

type GetDataFromCodeRow struct {
	Url       string
	CreatedAt time.Time
}

func (q *Queries) GetDataFromCode(ctx context.Context, code string) (GetDataFromCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getDataFromCode, code)
	var i GetDataFromCodeRow
	err := row.Scan(&i.Url, &i.CreatedAt)
	return i, err
}

const incrementClicksFromCode = `-- name: IncrementClicksFromCode :exec
UPDATE links
SET click_count = click_count + 1
WHERE code = $1
`

func (q *Queries) IncrementClicksFromCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, incrementClicksFromCode, code)
	return err
}

const insertCode = `-- name: InsertCode :one
INSERT INTO links (
    code, url
) VALUES (
    $1, $2
)
RETURNING code, created_at, click_count
`

type InsertCodeParams struct {
	Code string
	Url  string
}

type InsertCodeRow struct {
	Code       string
	CreatedAt  time.Time
	ClickCount int64
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) (InsertCodeRow, error) {
	row := q.db.QueryRowContext(ctx, insertCode, arg.Code, arg.Url)
	var i InsertCodeRow
	err := row.Scan(&i.Code, &i.CreatedAt, &i.ClickCount)
	return i, err
}
